server:
  port: 9005


spring:
  jpa:
    properties:
      hibernate:
        new_generator_mappings: false
        format_sql: true
    database: mysql
    show-sql: true
    #???????????????????????????????????????????????????_??????????userName??user_name
    hibernate:
      ddl-auto: update
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blps
    username: postgres
    password: s336262


